### ISSUE TITLE
So

### ISSUE THREAD

**Issue by m1chael31** [GenoX-Fome/funkin-utau#1]
When i go on the english patch i need to put in a download password

**Comment by GenoX-Fome** [comment]
You mean like, the .zip or the download page? Remember that the English patch can be found on the Wiki: https://download1.getuploader.com/g/60523ee9-1758-449e-a84b-79a8a010e467/utau_a5/35/utau_a5_35.zip
![image](https://user-images.githubusercontent.com/79883790/111512768-dc590900-872e-11eb-92b5-c671c00dce91.png)
If the .zip, you maybe download it from other site or something, since the English Patch zip dont needs any password (at least on WinRAR)
